# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('element_type', models.CharField(max_length=50)),
                ('battle_sprite', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('battle_sprite', models.URLField()),
                ('overworld_sprite', models.URLField()),
                ('names', models.TextField()),
                ('pokemon', models.ManyToManyField(related_name='trainers', to='trainers.Pokemon')),
            ],
        ),
    ]
