# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokedexEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex_entries', to='trainers.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pokemon', models.ManyToManyField(related_name='trainers', to='trainers.Pokemon')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainerclass',
            name='names',
        ),
        migrations.RemoveField(
            model_name='trainerclass',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='trainers.TrainerClass'),
        ),
    ]
