# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_auto_20171129_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='battle_sprite',
            field=models.URLField(default=''),
        ),
    ]
