# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_pokemon_battle_sprite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='stats_total',
        ),
    ]
