# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_auto_20171129_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleBattleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('battle_sprite', models.URLField()),
                ('overworld_sprite', models.URLField()),
                ('trainers', models.ManyToManyField(related_name='double_battles', to='trainers.TrainerClass')),
            ],
        ),
        migrations.RemoveField(
            model_name='pokedexentry',
            name='pokemon',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='PokedexEntry',
        ),
    ]
